### ISSUE TITLE
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'float64' in load_challenge_data

### ISSUE THREAD

**Issue by FilippoUslenghi** [physionetchallenges/python-example-2023#7]
This problem happens when `load_challenge_data` is called on a patient with no EEG records.

In fact `load_challenge_data` calls `get_recording_ids` that returns a numpy array of the recording ids of the patient.

In the case that the patient has at least one record available the entire array returned by `get_recording_ids` will be an array of strings; in the case that the patient has no records available the returned array will be an array of `np.nan`.

This happens because in https://github.com/physionetchallenges/python-example-2023/blob/30eac61cb1bda96f4163afc1fc299e47a2e3f5b8/helper_code.py#L190
if `variables` is a list of only np.nan values, the resulting array would be a float array of np.nan, instead if at least one value in the list is a string (i.e. a record of EEG data is available), then the returned array will be a string array. (at least this is what happens to me with numpy==1.24.2)

So when load_challenge_data is called on a patient with no records available, the array of recording ids will be an array of np.nan (i.e. a float value) and the condition of this statement will be True
https://github.com/physionetchallenges/python-example-2023/blob/30eac61cb1bda96f4163afc1fc299e47a2e3f5b8/helper_code.py#L33

and so the next line would try to execute a join with a float argument, thus returning the error of the title.
https://github.com/physionetchallenges/python-example-2023/blob/30eac61cb1bda96f4163afc1fc299e47a2e3f5b8/helper_code.py#L34

I would suggest to change the condition of the if statement at line 33 using your custom function `is_nan()`, so it would be `if not is_nan(recording_id):`

**Comment by matthewreyna** [comment]
Thanks for quickly finding and diagnosing this issue! Yes, this error was an unintended consequence of another bug fix from yesterday. Indeed, the suggested change (using the `is_nan()` function) fixes this issue, and I have pushed the suggested change to this repository.
