### ISSUE TITLE
Integer overflow in helper_code.load_recording_data

### ISSUE THREAD

**Issue by wenh06** [physionetchallenges/python-example-2023#8]
The data type of loaded values using `scipy.io.loadmat` from the `.mat` data files is `int16`. Subtraction using `baseline` (or `offset`) might result in an integer overflow. An example is illustrated as follows:

![image](https://github.com/physionetchallenges/python-example-2023/assets/8778305/b08c8e4d-6ab3-4138-89bb-c0067a9f26d2)

Perhaps a data type conversion (e.g. `int32`, `float32`) should be immediately performed after `scipy.io.loadmat`.

**Comment by wenh06** [comment]
e.g.
https://github.com/physionetchallenges/python-example-2023/blob/8035007df819f7f951c4e7a02eeb865f5a404db2/helper_code.py#L100
=>
```python
data = np.asarray(sp.io.loadmat(signal_file)["val"], dtype=np.int32)
```

**Comment by wenh06** [comment]
Perhaps values like `-32768`, and `32767` in the `.mat` files are already truncated?

**Comment by matthewreyna** [comment]
Thank you for digging into the code.

Yes, while the `data` variable and the `offset` variables have different data types and may be promoted when added/subtracted, it would be better for this to explicitly occur, so I have made this change.

I am not sure about your comment about `-32768` and `32767`, which indeed gives the range of a 16-bit signed, which we used to store the data.

Thank you again, and please contact us on the Challenge forum or by email to make it easier for us to address issues in the future.

**Comment by wenh06** [comment]
> Thank you for digging into the code.
> 
> Yes, while the `data` variable and the `offset` variables have different data types and may be promoted when added/subtracted, it would be better for this to explicitly occur, so I have made this change.
> 
> I am not sure about your comment about `-32768` and `32767`, which indeed gives the range of a 16-bit signed, which we used to store the data.
> 
> Thank you again, and please contact us on the Challenge forum or by email to make it easier for us to address issues in the future.

I mean if one meets values like `-32768` and `32767`, perhaps the true signal digital values are out of this range (not sure, because it is also related to the hardware) and were truncated into this int16 range when corresponding recordings were saved.
